// Types for the Excel scenario shadow runner. The fixture is generated by
// `scripts/build-excel-fixtures.ts` from `data/gatiod_injury_scenario_catalogue.xlsx`
// and committed at `scenarios.generated.json`. See ADR-0001.

import type { GatiodSystemKey } from "../../../src/v2/contracts.js";

/**
 * One of the five expected outcome classes per ADR-0001. CNS/visual rows use
 * `legacy_deferred` per ADR-0002; everything else uses one of the first four.
 */
export type ExpectedOutcomeClass =
  | "exact_calculation"
  | "clarification_required"
  | "unsupported_safe_fail"
  | "routing_only"
  | "legacy_deferred";

/**
 * One scored component within a scenario row. Single-system rows have one
 * component; cross-system rows have one component per non-empty Component N.
 */
export interface ExcelScenarioComponent {
  system: GatiodSystemKey;
  /** Human-readable injury description for this component, used as input. */
  injuryDescription: string;
  /** Expected PI% for this component (when the workbook gives an exact value). */
  expectedPiPercent?: number;
  /** Expected PI% range (lo, hi inclusive) when the workbook value is a range
   *  like "0-10%". Used by the grader: an observed PI within [lo, hi] counts
   *  as an exact-calculation match. Mutually exclusive with expectedPiPercent. */
  expectedPiRange?: [number, number];
  /** Outcome class chosen by the heuristic classifier. */
  heuristicOutcomeClass: ExpectedOutcomeClass;
  /** Final outcome class after override file resolution. */
  outcomeClass: ExpectedOutcomeClass;
  /** True if an override row replaced the heuristic class. */
  overrideApplied: boolean;
  /** Whether this component contributes to its system's promotion gate. */
  countsTowardSystemGate: boolean;
  /** Whether this component contributes to the cross-system E2E rate. */
  countsTowardCrossSystemE2E: boolean;
}

/**
 * One scenario row from the workbook. `inputText` is the doctor-facing
 * description used as the assistant's input. `rowId` is `"<sheet>:<sheet-row-id>"`
 * — used to key into the override file.
 */
export interface ExcelScenarioFixture {
  rowId: string;
  sheetName: "Scenario Catalogue" | "Specific Scenarios" | "Cross-System Scenarios";
  inputText: string;
  /** Final combined PI% (cross-system rows) or single-system PI% otherwise. */
  expectedFinalPiPercent?: number;
  components: ExcelScenarioComponent[];
  /**
   * Row-level classification. `legacy_deferred_cross_system` is reserved for
   * cross-system rows whose every component is `legacy_deferred` (e.g.
   * CNS + Visual) and which therefore contribute nothing to any gate.
   */
  rowClassification:
    | "single_system"
    | "cross_system"
    | "legacy_deferred_cross_system";
}

/** Override entry keyed by `<sheet>:<rowId>` in `outcomeClassOverrides.json`. */
export interface OutcomeClassOverride {
  /** Index of the component to override (0 for single-system rows). */
  componentIndex: number;
  outcomeClass: ExpectedOutcomeClass;
  reason: string;
}

/**
 * Build-time event emitted by the generator when an override replaces a
 * heuristic classification. Written to `outcome-class-report.generated.json`
 * so the heuristic's accuracy can be tracked over time.
 */
export interface OutcomeClassOverriddenEvent {
  rowId: string;
  sheetName: ExcelScenarioFixture["sheetName"];
  componentIndex: number;
  heuristicClass: ExpectedOutcomeClass;
  overrideClass: ExpectedOutcomeClass;
  reason: string;
}

/** The shape of the committed fixture JSON. */
export interface ExcelFixtureFile {
  sourceWorkbook: string;
  sourceSha256: string;
  generatedAt: string;
  sheetCounts: Record<string, number>;
  scenarios: ExcelScenarioFixture[];
}
