/**
 * claimsDex Integration Adapter
 *
 * Clean interfaces that claimsDex plugs into when integrating the GATIOD chat.
 * For standalone MVP, these use local implementations.
 * For claimsDex, each is replaced with the platform's native service.
 */

// ─── Auth Adapter ────────────────────────────────────────────────────────────
// Standalone: no auth. claimsDex: Firebase Auth middleware.

export interface AuthUser {
  userId: string;
  email: string;
  role: string;
}

export interface AuthAdapter {
  /** Verify request and return user, or null if unauthenticated. */
  verifyRequest(headers: Record<string, string | string[] | undefined>): Promise<AuthUser | null>;
}

export const standaloneAuth: AuthAdapter = {
  async verifyRequest() {
    // No auth in standalone mode
    return null;
  },
};

// ─── Session DB Adapter ──────────────────────────────────────────────────────
// Standalone: local SQLite. claimsDex: shared SQLite/PostgreSQL via db.ts.

export interface SessionDbAdapter {
  save(sessionId: string, data: unknown): Promise<void>;
  load(sessionId: string): Promise<unknown | null>;
  delete(sessionId: string): Promise<void>;
}

// The standalone implementation is in src/db/sessionStore.ts.
// claimsDex replaces this with its own db.prepare() calls.

// ─── RAG Adapter ─────────────────────────────────────────────────────────────
// Standalone: simple keyword search. claimsDex: gatiodHybridRetriever (BM25 + embeddings).

export interface RagAdapter {
  searchDictionary(query: string): Promise<unknown[]>;
  searchChapter(query: string, chapter?: number): Promise<unknown[]>;
}

// The standalone implementation is in src/rag/dictionaryIndex.ts.
// claimsDex replaces this with gatiodHybridRetriever.ts.

// ─── MR Export Adapter ───────────────────────────────────────────────────────
// Standalone: markdown export. claimsDex: DMR pipeline with TrustVC PDF.

export interface MrExportAdapter {
  /** Generate a medical report from assessment results. */
  generateReport(sessionId: string, results: Record<string, unknown>): Promise<{
    format: "markdown" | "pdf";
    content: string | Buffer;
    filename: string;
  }>;
}

export const standaloneMrExport: MrExportAdapter = {
  async generateReport(_sessionId, results) {
    // Basic markdown export (same as ReportExport component generates)
    const pi = (results.finalPercent as number) ?? 0;
    const lines = [
      `# GATIOD Assessment Report`,
      `**Date:** ${new Date().toISOString().split("T")[0]}`,
      `**Final PI:** ${pi}%`,
      "",
      "---",
      "*Generated by GATIOD Chat Assessment Assistant*",
    ];
    return {
      format: "markdown",
      content: lines.join("\n"),
      filename: `gatiod-assessment-${new Date().toISOString().split("T")[0]}.md`,
    };
  },
};

// ─── Feature Flags ───────────────────────────────────────────────────────────

export function isGatiodChatEnabled(): boolean {
  return process.env.GATIOD_CHAT_ENABLED !== "false";
}

// ─── Integration Config ──────────────────────────────────────────────────────

export interface IntegrationConfig {
  auth: AuthAdapter;
  mrExport: MrExportAdapter;
  /** Feature flag name in claimsDex config system. Suggested: VITE_GATIOD_CHAT_ASSESSMENT */
  featureFlagKey: string;
}

export const standaloneConfig: IntegrationConfig = {
  auth: standaloneAuth,
  mrExport: standaloneMrExport,
  featureFlagKey: "GATIOD_CHAT_ENABLED",
};
