import { useState, useMemo } from "react";
import { Box, Paper, Typography, Button, TextField, Collapse, IconButton } from "@mui/material";
import DownloadIcon from "@mui/icons-material/Download";
import EditNoteIcon from "@mui/icons-material/EditNote";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import ExpandLessIcon from "@mui/icons-material/ExpandLess";
import DescriptionIcon from "@mui/icons-material/Description";

interface ReportExportProps {
  result: Record<string, unknown>;
}

function generateReport(result: Record<string, unknown>): string {
  const lines: string[] = [];
  const now = new Date().toISOString().split("T")[0];
  const pi = result.finalPercent as number;

  lines.push("# GATIOD Assessment Report");
  lines.push(`**Date:** ${now}`);
  lines.push(`**Final PI:** ${pi}%`);
  lines.push("");

  const categories = [
    { key: "amputation", label: "Amputations" },
    { key: "rom", label: "Range of Motion" },
    { key: "neurological", label: "Neurological" },
    { key: "dbe", label: "Diagnosis-Based Estimates" },
  ];

  for (const cat of categories) {
    const data = result[cat.key] as { rawPercent: number; notes: string[] } | undefined;
    if (!data) continue;
    lines.push(`## ${cat.label}: ${data.rawPercent}%`);
    if (data.notes.length > 0) {
      for (const note of data.notes) lines.push(`- ${note}`);
    } else {
      lines.push("- None reported");
    }
    lines.push("");
  }

  const conflicts = result.dbeRomConflicts as { joint: string; romPercent: number; dbePercent: number; winner: string }[];
  if (conflicts && conflicts.length > 0) {
    lines.push("## Conflict Resolution");
    for (const c of conflicts) {
      lines.push(`- ${c.joint}: ROM ${c.romPercent}% vs DBE ${c.dbePercent}% → ${c.winner} retained`);
    }
    lines.push("");
  }

  const cvc = result.cvcInputs as number[];
  if (cvc && cvc.length > 1) {
    lines.push("## CVC Combination");
    lines.push(`- Inputs: ${cvc.join("%, ")}%`);
    lines.push(`- Combined: ${pi}%`);
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by GATIOD Chat Assessment Assistant*");
  return lines.join("\n");
}

export default function ReportExport({ result }: ReportExportProps) {
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState(false);
  const initialReport = useMemo(() => generateReport(result), [result]);
  const [report, setReport] = useState(initialReport);

  const handleDownload = () => {
    const blob = new Blob([report], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `gatiod-assessment-${new Date().toISOString().split("T")[0]}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Paper sx={{ mb: 1, border: "1px solid", borderColor: "divider", overflow: "hidden" }}>
      <Box
        onClick={() => setOpen(!open)}
        sx={{ display: "flex", alignItems: "center", gap: 1, px: 2, py: 1, cursor: "pointer", "&:hover": { bgcolor: "action.hover" } }}
      >
        <DescriptionIcon sx={{ fontSize: 18, color: "text.secondary" }} />
        <Typography variant="subtitle2" sx={{ flex: 1, fontWeight: 600, fontSize: "0.85rem" }}>
          Assessment Report
        </Typography>
        <Button size="small" startIcon={<DownloadIcon />} onClick={(e) => { e.stopPropagation(); handleDownload(); }} sx={{ fontSize: "0.78rem" }}>
          Download .md
        </Button>
        <IconButton size="small">
          {open ? <ExpandLessIcon fontSize="small" /> : <ExpandMoreIcon fontSize="small" />}
        </IconButton>
      </Box>
      <Collapse in={open}>
        <Box sx={{ px: 2, pb: 2 }}>
          {editing ? (
            <Box sx={{ display: "flex", flexDirection: "column", gap: 1 }}>
              <TextField
                fullWidth
                multiline
                minRows={8}
                maxRows={20}
                value={report}
                onChange={(e) => setReport(e.target.value)}
                sx={{ "& .MuiInputBase-input": { fontFamily: "'JetBrains Mono', monospace", fontSize: "0.82rem", lineHeight: 1.6 } }}
              />
              <Box sx={{ display: "flex", gap: 1 }}>
                <Button size="small" variant="contained" onClick={() => setEditing(false)}>Done editing</Button>
                <Button size="small" onClick={() => { setReport(initialReport); setEditing(false); }}>Reset</Button>
              </Box>
            </Box>
          ) : (
            <Box>
              <Box
                sx={{
                  p: 2,
                  bgcolor: "#f8f9fb",
                  borderRadius: 1,
                  fontFamily: "'JetBrains Mono', monospace",
                  fontSize: "0.82rem",
                  lineHeight: 1.6,
                  whiteSpace: "pre-wrap",
                  color: "text.primary",
                  maxHeight: 300,
                  overflow: "auto",
                }}
              >
                {report}
              </Box>
              <Button size="small" startIcon={<EditNoteIcon />} onClick={() => setEditing(true)} sx={{ mt: 1, fontSize: "0.78rem" }}>
                Edit before download
              </Button>
            </Box>
          )}
        </Box>
      </Collapse>
    </Paper>
  );
}
